version: 2
updates:
  - package-ecosystem: "npm" # Busca dependencias en package.json
    directory: "/" # Directorio ra√≠z
    schedule:
      interval: "weekly" # Cada semana
    labels:
      - "dependencies"
